[SQUASHED]Mass Revert of CM's Qs Drag Panel
--Bye bye DragPanel . We had a nice laggy fun run
--Add Back Stock Aosp panels
--Add Back all Customizations except for Draggable Tiles
--Bring Back Tuner
--Fix Tuner NPE credits : @westcripp
--QS :Make tiles visible behind of transparent detail view  @westcripp

Avoid NPE in Array Adapter

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:394).

Change-Id: Id13b624f5b4b7ab960f731e156312c60fe3919cf

DirtyUnicorns/android_frameworks_base@bbb9047

Remove Tuner Settings From DashBoard

6de435a

Fix NP Color NPE :-

@westcripp

https://github.com/ResurrectionRemix/android_frameworks_base/commit/d68220b6b704f06c2cd5162338b1d9456ab3d7c8

Fix Wifi ,BT, Expanded Desktop Tiles Alignment

Thanks to Alex Cruz (Mazda--)

Fix Borken Qs Tiles

Revert https://github.com/ResurrectionRemix/android_frameworks_base/commit/3b3385aafc8c9025cf78c33018ab08e18a938a6d

Revert  "SysUI: Clean up objects when recreating statusbar"
(suspected to cause lag)

Option to Turn of Main tiles

http://gerrit.dirtyunicorns.com/#/c/24766/
Author : Jorge Martin Espinosa <jorgemartinespinosa@gmail.com>

Drop the animated settings icon

https://github.com/ResurrectionRemix/android_frameworks_base/commit/b3b3cd7304f6bf84a36eacb207da8f03f3f0a82e

since we have effectively killed the ui tuner lets revert to the old setting icon instead
of the new unused animated version, also lets make sure tuner service always returns true
as we are launching it externally now.

Author = beanstown106 <nbenis106@gmail.com>

SystemUI: Set Number Of Qs Columns

https://github.com/ResurrectionRemix/android_frameworks_base/commit/61dd0c8146b69e2340a8e22596ee4c71042dbaae

Author :- Randall Rushing <randall.rushing@gmail.com>
Change-Id: I12fc866c46b576c495fbf84deafeb2dd18e1365a

Incase ive missed any credits please let me know

Signed-off-by: Varun Date <date.varun123@gmail.com>