Fix systemUI FC when using the Language QS tile (#212)
* Fix systemUI FC when using the Language QS tile

systemUI FC when using the Language QS tile. The language doesn't change (english to french).

java.lang.SecurityException: Permission Denial: updateConfiguration() from pid=7976, uid=10033 requires android.permission.CHANGE_CONFIGURATION
at android.os.Parcel.readException(Parcel.java:1684)
at android.os.Parcel.readException(Parcel.java:1637)
at android.app.ActivityManagerProxy.updatePersistentC onfiguration(ActivityManagerNative.java:6008)
at com.android.internal.app.LocalePicker.updateLocale s(LocalePicker.java:306)
at com.android.systemui.qs.tiles.LocaleTile$1.run(Loc aleTile.java:93)
at android.os.Handler.handleCallback(Handler.java:751 )
at android.os.Handler.dispatchMessage(Handler.java:95 )
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61 )

* Pie: Fix FC after reboot with french language

Enable pie, reboot the phone with automatic translation = FC